server:
  port: 8090
  servlet:
    context-path: /
spring:
  application:
    name: gy
  profiles:
    active: dev
  datasource:
    username: sa
    password: root
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=nfhis
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
mybatis:
    type-aliases-package: com.stopec.gy.pojo.*
    mapper-locations: classpath:/mybatis/Dao/*Mapper.java
logging:
  config: classpath:logback-spring.xml


