spring.dynamic:
  url: http://127.0.0.1:7003/yhjypt/services/yinHaiBusiness?wsdl
  namespace: http://webservice.common.yinhai.com/
  username: gygly
  password: 123456
  method: callBusiness
jdbc:
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://192.168.16.105:1433;DatabaseName=nfhis
  username: sa
  password: root
  DB_MAXCONN: 10
health:
  check: no