spring.dynamic:
  url: http://127.0.0.1:7003/yhjypt/services/yinHaiBusiness?wsdl
  namespace: http://webservice.common.yinhai.com/
  username: gygly
  password: 123456
  method: callBusiness
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://10.211.55.5:32306/gy?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Hongkong
  username: root
  password: 123456
  DB_MAXCONN: 10
health:
  check: no